#define RELEASE 1
#define DEBUG 0

#define COMPRESSION_ENABLED 1
#define COMPRESSION_DISABLED 0

#define SIGNATURE_ENABLED 1
#define SIGNATURE_DISABLED 0

#define UNINSTALL_REQUIRED 1
#define UNINSTALL_IGNORED 0
